# Generated by Django 4.0.6 on 2022-07-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='메롱', max_length=50, null=True)),
                ('view_auth', models.IntegerField(blank=True, default=0, null=True)),
                ('color', models.CharField(blank=True, default='#808080', max_length=20, null=True)),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=20, null=True)),
                ('thumb_nail', models.ImageField(blank=True, null=True, upload_to='todo/')),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todomates.category')),
            ],
        ),
    ]
